controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    projectionX = 0
    projectionY = -200
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile2 = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . b d b c . . . . . 
        . . . . b b c 5 5 5 c b b . . . 
        . . . . b 5 5 5 1 5 5 5 b . . . 
        . . . c c 5 5 5 1 5 5 5 c c . . 
        . . b b 5 5 5 1 1 1 5 5 5 b b . 
        . . d d 5 1 1 1 1 1 1 1 5 d d . 
        . . b b 5 5 5 1 1 1 5 5 5 b b . 
        . . . c c 5 5 5 1 5 5 5 c c . . 
        . . . . b 5 5 5 1 5 5 5 b . . . 
        . . . . b b c 5 5 5 c b b . . . 
        . . . . . . c b d b c . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, 50, 50)
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    projectionX = -200
    projectionY = 0
})
function scorePoint () {
    let value: tiles.Location = null
    for (let value of tiles.getTilesByType(sprites.dungeon.greenOuterWest2)) {
        colectible1 = sprites.create(img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            .......22...22......
            ......2322.2222.....
            ......232222222.....
            ......222222222.....
            .......22222b2......
            ........222b2.......
            .........222........
            ..........2.........
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            `, SpriteKind.Food)
    }
    tiles.placeOnTile(colectible1, value)
    tiles.setTileAt(value, assets.tile`transparency16`)
}
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    current_level += 1
    changelevel(current_level)
})
function changelevel (level_number: number) {
    if (level_number == 1) {
        tiles.setCurrentTilemap(tilemap`level2`)
    } else if (level_number == 2) {
        tiles.setCurrentTilemap(tilemap`level4`)
    } else if (level_number == 3) {
        tiles.setCurrentTilemap(tilemap`level6`)
    } else if (level_number == 4) {
        tiles.setCurrentTilemap(tilemap`level1`)
    } else if (level_number == 5) {
        tiles.setCurrentTilemap(tilemap`level0`)
    }
    spawnEnemies()
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.stairLadder)
}
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    projectionX = 200
    projectionY = 0
})
function spawnEnemies () {
    for (let value of tiles.getTilesByType(sprites.builtin.forestTiles0)) {
        enemy1 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        tiles.placeOnRandomTile(enemy1, sprites.builtin.forestTiles0)
        enemy1.follow(mySprite, 30)
    }
}
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    projectionX = 0
    projectionY = 200
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    sprites.destroy(mySprite, effects.confetti, 500)
    info.changeScoreBy(1)
})
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.greenOuterWest2, function (sprite, location) {
    game.gameOver(true)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(mySprite, effects.fire, 500)
    sprites.destroy(mySprite)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprites.destroy(otherSprite)
    info.changeLifeBy(-1)
})
let enemy1: Sprite = null
let colectible1: Sprite = null
let projectile2: Sprite = null
let projectionY = 0
let projectionX = 0
let current_level = 0
let mySprite: Sprite = null
scene.setBackgroundColor(3)
mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . f f f f f f . . . . . 
    . . . . f 5 4 5 5 4 5 f . . . . 
    . . . f e 4 5 5 5 5 4 e f . . . 
    . . f b 3 e 4 4 4 4 e 3 b f . . 
    . f e 3 3 3 3 3 3 3 3 3 3 e f . 
    . f 3 3 e b 3 e e 3 b e 3 3 f . 
    . f b 3 f f e e e e f f 3 b f . 
    . f b b f b f e e f b f b b f . 
    . f b b e 1 f 4 4 f 1 e b b f . 
    . f b b e e 4 4 4 4 4 f b b f . 
    . . f 4 4 4 e d d d b f e f . . 
    . . f e 4 4 e d d d d c 4 e . . 
    . . . f e e d d b d b b f e . . 
    . . . f f 1 d 1 d 1 1 f f . . . 
    . . . . . f f f f f f . . . . . 
    `, SpriteKind.Player)
let enemy2 = sprites.createProjectileFromSide(img`
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ......fd11111111df......
    ......fddd1111dddf......
    ......fbdbfddfbdbf......
    ......fcdcf11fcdcf......
    .......fb111111bf.......
    ......fffcdb1bdffff.....
    ....fc111cbfbfc111cf....
    ....f1b1b1ffff1b1b1f....
    ....fbfbffffffbfbfbf....
    .........ffffff.........
    ...........fff..........
    ........................
    ........................
    ........................
    ........................
    `, -80, 0)
enemy2.setKind(SpriteKind.Enemy)
controller.moveSprite(mySprite)
scene.cameraFollowSprite(mySprite)
current_level = 1
changelevel(1)
info.setLife(3)
info.startCountdown(90)
